apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "student-stack.fullname" . }}
  labels:
    {{- include "student-stack.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "student-stack.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "student-stack.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: DB_HOST
              value: {{ .Values.db.host | quote }}
            - name: DB_PORT
              value: {{ .Values.db.port | quote }}
            - name: DB_NAME
              value: {{ .Values.db.name | quote }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.app.name }}
                  key: {{ .Values.secrets.app.keys.userKey }}
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.app.name }}
                  key: {{ .Values.secrets.app.keys.passKey }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "student-stack.fullname" . }}
  labels:
    {{- include "student-stack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "student-stack.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
