# .github/workflows/build-and-bump.yml
name: Build image and bump Helm tag

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "student-stack/values.yaml"
  workflow_dispatch: {}

permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.meta.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Compute tag
        id: meta
        run: echo "tag=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: kiril011/student-api:${{ steps.meta.outputs.tag }}

  bump-helm:
    needs: build-and-push
    runs-on: [self-hosted, linux]
    env:
      VALUES_FILE: student-stack/values.yaml
      IMAGE_REPO:  kiril011/student-api
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Install yq (local)
        run: |
          mkdir -p "$RUNNER_TEMP/bin"
          curl -fsSL https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64 -o "$RUNNER_TEMP/bin/yq"
          chmod +x "$RUNNER_TEMP/bin/yq"
          echo "$RUNNER_TEMP/bin" >> "$GITHUB_PATH"
      - name: Update values.yaml
        run: |
          yq -i '.image.repository = env(IMAGE_REPO)' "$VALUES_FILE"
          yq -i '.image.tag = "${{ needs.build-and-push.outputs.tag }}"' "$VALUES_FILE"
          git --no-pager diff -- "$VALUES_FILE" || true
      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "$VALUES_FILE"
          git commit -m "[skip ci] chore(helm): bump image tag to ${{ needs.build-and-push.outputs.tag }}" || exit 0
          git pull --rebase
          git push
